<template>
    <main class="cs--page cs--dashboard--2fa">
        <div class="cs--container">
            <h1 class="cs--page__title">2 Factor Authentication</h1>
            <div class="cs--page-side-wrapper">
                <form class="cs--dashboard-form">
                    <div class="cs--dashboard-form__result">
                        <div class="cs--dashboard-form__result-img">
                            <img src="/img/img-check.svg" alt=""/>
                        </div>
                        <h2 class="cs--dashboard-form__result-title">
                            The setup is complete!
                        </h2>
                        <p class="cs--dashboard-form__result-text">
                            You will be required to enter the one time code generated by
                            Google Authenticator the next time you login.
                        </p>
                    </div>
                    <div class="cs--dashboard-form__btn-group">
                        <router-link
                            to="/"
                            tag="button"
                            class="cs--btn cs--btn--grad-blue ml-auto"
                        >
                            Done
                        </router-link>
                    </div>
                </form>

                <aside class="cs--page-side">
                    <h3 class="cs--page-side__title">FAQs</h3>
                    <ul class="cs--page-side__item-list">
                        <li class="cs--page-side__item">
                            <a href="javasript:void(0)" class="cs--page-side__link"
                            >What is 2FA?</a
                            >
                        </li>

                        <li class="cs--page-side__item">
                            <a href="javasript:void(0)" class="cs--page-side__link"
                            >How do I link an exchange?</a
                            >
                        </li>

                        <li class="cs--page-side__item">
                            <a href="javasript:void(0)" class="cs--page-side__link"
                            >Can I create a new exchange account through
                                CryptoSystem?</a
                            >
                        </li>

                        <li class="cs--page-side__item">
                            <a href="javasript:void(0)" class="cs--page-side__link"
                            >What are exchange APIs?</a
                            >
                        </li>

                        <li class="cs--page-side__item">
                            <a href="javasript:void(0)" class="cs--page-side__link"
                            >Do you offer a referral rewards program?</a
                            >
                        </li>

                        <li class="cs--page-side__item">
                            <a href="javasript:void(0)" class="cs--page-side__link"
                            >Can I deposit or withdraw assets from CryptoSystem?</a
                            >
                        </li>

                        <li class="cs--page-side__item">
                            <a
                                href="javasript:void(0)"
                                class="cs--page-side__link cs--page-side__link--accent"
                            >Visit Support Center</a
                            >
                        </li>
                    </ul>
                </aside>
            </div>
        </div>
    </main>
</template>

<script>
export default {
    name: "TwoFactorAuthStep4"
}
</script>

<style scoped>

</style>
